services:
  frontend:
    build : ./client 
    image: student-repo-client
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env
    networks:
      - student-repo-network
    
  backend:
    build : ./server
    image: student-repo-server
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - SECRET_KEY=mykey123
      - MONGODBURL=mongodb://root:root@mongodb:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.5.2
    networks:
      - student-repo-network
    
  mongodb:
    image : mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      - student-repo-network
    volumes:
      - mongo-data:/data/db

networks:
  student-repo-network:
    driver: bridge

volumes:
  mongo-data: